updated tile verification

diff --git a/.github/workflows/build-and-test.yaml b/.github/workflows/build-and-test.yaml
--- a/.github/workflows/build-and-test.yaml
+++ b/.github/workflows/build-and-test.yaml
@@ -79,14 +79,18 @@ jobs:
       run : |
         sha1sum  *.png
         sha1sum  --check  <<EOF
-        8aeddc612a8a4fbc480dbd3241739ccf19938f11 *000.png
-        194ae70330d54bc0ab95441e0c46774232e3c4a4 *100.png
-        7d78800b607ad769cf0280744f04dfd92e31ffd1 *101.png
-        62ae1081b8613b542fb650136ff15ffac9c7818d *110.png
-        3f72d900803266ce8e7fe27d25eb251f29cba3d0 *111.png
         c226ca747874fb1307eef853feaf9d8db28cef2b *empty.png
         EOF
+        ! diff  empty.png  000.png      ||  (  >&2  echo  "ERROR: 000.png is empty"      &&  exit 1  )
+        ! diff  empty.png  100.png      ||  (  >&2  echo  "ERROR: 100.png is empty"      &&  exit 1  )
+        ! diff  empty.png  101.png      ||  (  >&2  echo  "ERROR: 101.png is empty"      &&  exit 1  )
+        ! diff  empty.png  110.png      ||  (  >&2  echo  "ERROR: 110.png is empty"      &&  exit 1  )
+        ! diff  empty.png  111.png      ||  (  >&2  echo  "ERROR: 111.png is empty"      &&  exit 1  )
         ! diff  empty.png  example.png  ||  (  >&2  echo  "ERROR: example.png is empty"  &&  exit 1  )
+        if [ `sha1sum   *.png  |  cut  -d ' '  -f 1  |  sort  |  uniq  |  wc  -l`  !=  7 ] ; then
+          >&2  echo  "ERROR: tile checksums are not unique"
+          exit 2
+        fi
     -
       name: Cleanup
       run : |
